# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [36]:
# No code solution (reading)
import torch
torch.__version__

'2.8.0+cu126'

### 2. Create a random tensor with shape `(7, 7)`.


In [37]:
# Import torch
# --> imported in the previous cell

# Create random tensor
randTensor1 = torch.rand(size=(7,7))
randTensor1

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [38]:
# Create another random tensor
randTensor2 = torch.rand(size=(1,7))

# Perform matrix multiplication
multiplicated_matrix = torch.mm(randTensor1 , randTensor2.T)
randTensor2, multiplicated_matrix

(tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]]),
 tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [39]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
Tensor1 = torch.rand(size=(7,7))
Tensor2 = torch.rand(size=(1,7))


# Matrix multiply tensors
mm_after_seed = torch.mm(Tensor1 , Tensor2.T)

Tensor1 , Tensor2 , mm_after_seed

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [40]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [41]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

tensor_A , tensor_B

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [42]:
# Perform matmul on tensor_A and tensor_B
mm2  = torch.mm(tensor_A , tensor_B.T)
mm2


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

## I Can NOT get the exact val
## What is wrong ??

### 8. Find the maximum and minimum values of the output of 7.

In [43]:
# Find max
mm2.max()
# Find min
mm2.min()

mm2.max() , mm2.min()

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [44]:
# Find arg max
mm2.argmax()

# Find arg min
mm2.argmin()

mm2.argmax() , mm2.argmin()


################################

# if we want the exact position with the coordinates , the following code will explain

max_index = mm2.argmax()
min_index = mm2.argmin()

max_coords = torch.unravel_index(max_index, mm2.shape)
min_coords = torch.unravel_index(min_index, mm2.shape)

max_coords, min_coords


((tensor(0, device='cuda:0'), tensor(1, device='cuda:0')),
 (tensor(0, device='cuda:0'), tensor(0, device='cuda:0')))

##((tensor(0, device='cuda:0'), tensor(1, device='cuda:0')),            
### `max_coords in row 0 , column 1`
##(tensor(0, device='cuda:0'), tensor(0, device='cuda:0')))           
### `min_coords in row 0 , column 0`



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rndm_torch = torch.rand(1, 1, 1, 10)

# Remove single dimensions
rndm_torch_squeezed = rndm_torch.squeeze()

# Print out tensors and their shapes
rndm_torch , rndm_torch.shape , rndm_torch_squeezed , rndm_torch_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

## Done الحمد لله✔️